name: Deploy to Hostpoint
on:
  push:
    branches:
      - hostpoint
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.73.0"
      
      - name: Build
        run: cd exampleSite && hugo --gc --themesDir ../..

      - name: Upload to Hostpoint
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.HP_SERVER }}
          username: ${{ secrets.HP_USER }}
          password: ${{ secrets.HP_DEPLOY_PASSWORD }}
          local-dir: ./public/
          dry-run: true
